version: '2'

services:
  workspace:
    image: node-workspace:8.11.2
    build: ./docker/workspace-image
    ports:
      - 4200:4200
    volumes:
      - ./:/workspace
    command: tail -f /dev/null
    